### ISSUE TITLE
Recognise 6-position postcodes in addresses in the Netherlands (without spaces)

### ISSUE THREAD

**Issue by emacgillavry** [pelias/parser#127]
Typically, addresses in the Netherlands have 4 digits, followed by 0 or 1 space, followed by 2 alphanumeric characters, e.g. "7512EC" or "7512 EC". The alphanumeric characters should not be "SA", "SD" or "SS": 

    /^[1-9][0-9]{3} ?(?!sa|sd|ss)[a-z]{2}$/i;

This bug is to track the first case, i.e. "7512EC", as part of PR #126 .

**Comment by missinglink** [comment]
The original pattern was sourced from the `libaddressinput` project, but yours looks better!
https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/NL
