### ISSUE TITLE
Street type '-plein' not recognised in Netherlands addresses

### ISSUE THREAD

**Issue by emacgillavry** [pelias/parser#128]
Passing in "Rembrandtplein, Amsterdam", only Amsterdam is handled as a locality, but Rembrandtplein is not recognised as a street.

This bug is to track "Rembrandtplein", as part of PR #126 .

**Comment by missinglink** [comment]
Is this suffix 'separable', ie. do you ever see street names in the form "Rembrandt Plein" (two words)?

If so then we have some code to handle generating alternative forms, as it's also common in DE/CH where people may interchangeably use "Hauptstrasse" or "Haupt Strasse" or "Haupt-strasse" if they're unsure which form it should be written in.

https://github.com/openvenues/libpostal/blob/master/resources/dictionaries/nl/concatenated_suffixes_separable.txt
