### ISSUE TITLE
NL: recognise 'sngl' as abbr for 'singel' without full stop

### ISSUE THREAD

**Issue by emacgillavry** [pelias/parser#165]
Abbreviated street names referring to '-singel', e.g. *Blekerssngl, Gouda* or *Herensngl, Haarlem* are only recognised as street names when there is a full stop at the end: _Blekers**sngl.**, Gouda_ or _Heren**sngl.**, Haarlem_.

Suggested change: add `singel|sngl` to the `concatenated_suffixes_separable.txt` file, as 'singel' also works as a street name by itself, e.g. *Singel, Amsterdam*.

**Comment by missinglink** [comment]
:+1: this seems safe to me, `-sngl` is an uncommon suffix and unlikely to cause undesired consequences.
