### ISSUE TITLE
Very high parser.solve response time

### ISSUE THREAD

**Issue by Joxit** [pelias/parser#57]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

I was using pelias/api#1287 and one of my clients sent me a query with a very long text (over 2000 char). The query blocked the API and I wanted to know why.... It was because of the parser that took 15 minutes to solve the query.
It was a bad client side integration, but it almost killed our services, so we need to go further and fix this.

:warning: This issue affects node v10 and below. With node v12+ the result takes 6-10 seconds :warning: 

Create a file named `parser_killer` and copy past this
```
hp({"activites_fr":["Week-end Gourman",["Séjour à 2 à l\'Hôtel L\'Escargot - L\'Escale Gourmande à Ruffec (16)","Séjour bien-être à 2 à Gourmandine à Saint-Andiol (13)","Séjour bien-être à 2 au Logis Hôtel Au Canard Gourmand à Samatan (32)","Séjour bien-être à La Bastide Gourmande à La Colle-sur-Loup (06)","Séjour bien-être en duo à Gourmandine à Saint-Andiol (13)","Séjour bien-être en duo au Logis Hôtel Au Canard Gourmand à Samatan (32)","Séjour bien-être et gourmand au Viest Hotel à Vicenza (Italie)","Séjour bien-être et gourmand pour 2 à l\'Amrâth Hotel & Thermen Born-Sittard**** à Born (Pays-Bas)","Séjour bien-être et gourmand pour 2 à l\'Auberge Le Relais*** à Corbion-sur-Semois (Luxembourg)","Séjour bien-être et gourmand pour 2 à l\'Hotel de la Vallée à Petit-Fays (Namur)"]],"categories_fr":["Week-end Gourman",["Séjour Gourmand"]],"coffrets_fr":["Week-end Gourman",["Week-end insolite et gourmand"]]});
```

Now run the CLI with twice the `parser_killer` file
```
node bin/cli.js $(cat parser_killer parser_killer)
```

Wait 15 minutes

The code hang here 
https://github.com/pelias/parser/blob/cd87ea401a75dc493fd3ac20e8429548a431ce1b/parser/Parser.js#L41-L42

It happens just after the `ExclusiveCartesianSolver` with over 1.8M solutions....

The issue only targets node v10 and below thanks to the [stable sort](https://v8.dev/blog/array-sort), but an address parsing in 6 second is still too high.

---
#### Here's what I think could be improved :trophy:

The input has more than 200 words
- we can add a limit for a text to be parsed / parse the first X words ?
- improve the `ExclusiveCartesianSolver` to produce at most 1-10k of solutions ?

**Comment by missinglink** [comment]
oh, good catch!
I thought https://github.com/pelias/parser/blob/master/parser/Parser.js#L44 would prevent this?

**Comment by missinglink** [comment]
Agh now I see, it's one line below where the problem is :P

**Comment by missinglink** [comment]
related: https://github.com/pelias/api/pull/1312

**Comment by Joxit** [comment]
Yes, and it's not crazy to sort before the slice :thinking: 
Oh, the text limit didn't work then ?

**Comment by missinglink** [comment]
The Pelias code is only applying to `/v1/search` at the moment, so we can address this issue at the `pelias/api` level for autocomplete too, but it might also be nice to handle it here, just in case anyone wants to use this library independently of Pelias proper.

I think 140 characters is a nice input limit, I'm not aware of a valid address which is longer.
We find that users send us all sorts of junk, like XML documents and whole CSV file etc, so we'll need to guard against that.

**Comment by orangejulius** [comment]
Very good catch indeed. So what is needed to reproduce this behavior? Any long input with many words? Or does it rely on specific character or word combinations?

I actually want to test it out on our staging environment to see if our infrastructure will detect the stalled API instances and replace them :)

**Comment by Joxit** [comment]
I'm also OK with 140 character (like twitter did).

In fact, it's a bit hard to reproduce the issue, I tried a few random words/localities with the same input length but the parser works fine...
As far as I know, the issue works well with the example I gave. So it may be a combination (with comma ?) of characters or words.

**Comment by Joxit** [comment]
It seems that pelias/api#1312 is not not used when we fallback on addressit because it override the clean text.

https://github.com/pelias/api/blob/bb0cb026412dbbc1fa36f3eb52664d10197ee23b/sanitizer/_text_addressit.js#L30-L42

**Comment by missinglink** [comment]
I added these commits today to mitigate this issue at the `pelias/api` level:

- https://github.com/pelias/api/pull/1287/commits/55b34cca2415fe57c0bf0753c86d739782dec72c
- https://github.com/pelias/api/pull/1350

**Comment by Joxit** [comment]
:rocket:
