### ISSUE TITLE
Parsing Czech Republic addresses

### ISSUE THREAD

**Issue by sch3399** [pelias/parser#83]
Hi team,
I have successfully installed pelias, but I have a problem with the autocomplete.
The query [street,city] `/autocomplete/?text=Nerudova 20,Praha` returns the correct result.
![image](https://user-images.githubusercontent.com/6430784/76075334-1c72a100-5f9d-11ea-900e-2af197f06a1f.png)

But the rotated query [city,street] `/autocomplete/?text=Praha,Nerudova 20` does not return any result and parser pelias creates bad query decomposition
![image](https://user-images.githubusercontent.com/6430784/76075276-02d15980-5f9d-11ea-9dfb-9d973508c438.png)

Is it possible to modify the configuration and get the same result as in the first case?

Search `/search?text=Praha,Nerudova 20` without autocomplete the result is correct in both cases, but the parser is not pelies, but libpostal
![image](https://user-images.githubusercontent.com/6430784/76075402-45933180-5f9d-11ea-99d2-3853344decc7.png)

Thank you for the advice

**Comment by sch3399** [comment]
1. The vast majority of streets in the Czech Republic have a one-word name without a prefix / suffix.
Korunní 810, Praha
Kájovská 68, Český Krumlov
Beethovenova 641/9, Brno

2. I don't know the likelihood of a reverse search [city, street], but it's not unusual.

3. Other neighboring states:
Divadelná 41/3, Trnava (Slovakia)
Szewska 6, Kraków (Poland)
Zadarska 17, Pula (Croatia)

Thank you very much for a possible solution

**Comment by missinglink** [comment]
@sch3399 I had a look at this today and I was able to get the parser working for the cases you provided.
If possible, could you please provide some more test cases?

**Comment by sch3399** [comment]
@missinglink I am sending other test cases for the Czech Republic

Ostrava, U Koupaliště 1570/10
Hradec Králové, Karla Čapka 694/5
Kolín, Pražská 3
Neratovice, Jungmannova 676
Králíky, Bedřicha Smetany 561
Prachatice, Dlouhá 93
Ronov nad Doubravou, Nábřežní 180
Brno, Orlí 517/22
Nový Jičín, Dvořákova 713/11
Praha, V Šáreckém údolí 53/27
Praha, Nad Panenskou 164/4
Rožmitál pod Třemšínem, Kpt. Jaroše 403
Klatovy, Jiráskova 15
Frýdek-Místek, Radniční 1244
Zlín, Rašínova 70
