### ISSUE TITLE
Long street names with street prefixes don't seem to parse

### ISSUE THREAD

**Issue by blackmad** [pelias/parser#98]
Hey team,

I've been playing with some Brazilian queries and have noticed the parser seems to have issues with parsing long street queries with a street prefix.

It seems like it might be something about more than two tokens after the prefix word, but I can't figure out where in the source code that logic might live.

Rua Raul Leite Magalhães, 65, Tapiraí - SP, 18180-000, Brazil
- no solution

Rua Raul Leite Magalhães
- only parses "Rua Rual Leite" as street

Rua Raul Leite, 65, Tapiraí - SP, 18180-000, Brazil
- deleted one word from street, works perfectly

Raul Leite Magalhães st, 65, Tapiraí - SP, 18180-000, Brazil
- added street suffix (I know, nonsense query) and it works perfectly

I noticed that in the source code, it says "Boulevard Charles de Gaulle" works, which it does, but I think it's getting lucky with "de" being a likely intersection connector word. "Boulevard Charles foobar Gaulle" fails in the same way, where only "Boulevard Charles foobar" is parsed as a street.

**Comment by Joxit** [comment]
Hi there, thank you for your issue :)

I added person classifier with #10 and I did not add compound surnames, it is not widespread in France :sweat_smile:
